version: '3'
services:
  mongodb:
    image: 'mongo'
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - mongodb-network
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks: 
      - mongodb-network

volumes :
  mongo-data:
    driver: local

networks:
  mongodb-network:
    driver: bridge
